---

  - hosts: web
    become: true

    tasks:
      - name: add PHP repo [1/2]
        apt: name=software-properties-common state=present
      - name: add PHP repo [2/2]
        apt_repository:
          repo: ppa:ondrej/php 
          state: present
      - name: Stop Apache prior to installing NGINX
        service: name=apache2 state=stopped enabled=no
        ignore_errors: yes 
      - name: install NGINX and PHP
        apt:
          name:
            - nginx
            - php7.4
            - php7.4-fpm
          state: present
          update_cache: yes
      - name: Enable NGINX
        service: name=nginx state=started enabled=yes
      - name: Upload test webpage
        copy:
          src: ./index.html
          dest: /var/www/html
          mode: 0755

...        
